name: polymorphism
description: "A Flutter Web portfolio showcasing the identity of an Ultimate Polymorphism — a visionary who balances engineering, art, and design."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  go_router: ^14.6.2
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.1
  responsive_framework: ^1.4.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
  assets: 
    - assets/images/
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
  uses-material-design: true