name: project_master_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  go_router: ^14.6.2
  auto_size_text: ^3.0.0
  dio: ^5.7.0
  loading_animation_widget: ^1.3.0
  animated_bottom_navigation_bar: ^1.3.3
  material_symbols_icons: ^4.2789.0
  package_info_plus: ^8.1.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  logger: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets: 
    - assets/images/
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
  uses-material-design: true