import { chromium } from 'playwright-core';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const REPO=path.resolve(fileURLToPath(import.meta.url),'../../..');
const OUT=path.join(REPO,'tool/prototype_render/out/balai-real'); fs.rmSync(OUT,{recursive:true,force:true}); fs.mkdirSync(OUT,{recursive:true});
const MIME={'.html':'text/html','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const fp=path.join(REPO,decodeURIComponent(req.url.split('?')[0]));if(!fs.existsSync(fp)){res.writeHead(404);return res.end();}res.writeHead(200,{'Content-Type':MIME[path.extname(fp).toLowerCase()]||'application/octet-stream'});fs.createReadStream(fp).pipe(res);});
await new Promise(r=>server.listen(7368,r));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-background-timer-throttling']});
const page=await browser.newPage({viewport:{width:1100,height:1000},deviceScaleFactor:3});
await page.goto('http://localhost:7368/'+'assets/works/Balai/Curated Drops Auction All Flows.html'.split('/').map(encodeURIComponent).join('/'),{waitUntil:'networkidle'}).catch(()=>{});
await sleep(3000);
const shotIframe=async(name)=>{const el=await page.$('iframe');if(el){await el.screenshot({path:path.join(OUT,name),scale:'device'});console.log('  saved',name);}else console.log('  no iframe',name);};
const top=async(t)=>{try{await page.locator(`text="${t}"`).first().click({timeout:1500});await sleep(1200);return true;}catch{return false;}};
const inside=async(t)=>{try{await page.frameLocator('iframe').locator(`text="${t}"`).first().click({timeout:1500});await sleep(1200);return true;}catch(e){console.log('  inner miss',t);return false;}};
await shotIframe('01-buyer-home.png');
await inside('demo: open drop'); await shotIframe('02-drop.png');
await inside('Heritage'); await shotIframe('03-lot.png');
await top('Seller'); await shotIframe('04-seller.png');
await top('Curator'); await shotIframe('05-curator.png');
await browser.close();server.close();console.log('done');
